# Generated by Django 3.2.2 on 2022-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
